[project]
name = "farm-localstack-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awscli>=1.40.23",
    "awscli-local>=0.22.0",
]
